/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlicuahangdienthoai;
import javax.swing.JPanel;
import javax.swing.JFrame;
import javax.swing.JTable;
import java.awt.Color;
import java.awt.Font;
import java.beans.Statement;
import javax.swing.BorderFactory;



/**
 *
 * @author ACER
 */

//import java.sql.DriverMagager;
//import java.sql.Connection;
//import java.sql.SQLException;
//import java.beans.Statement;
//import java.sql.ResultSet;
public class MainPage extends javax.swing.JFrame {
    int mouseX;
    int mouseY; 
    
    /**
     * Creates new form MainPage
     */
    public MainPage() {
        
        initComponents();
//        setBackground(new Color(0,0,0,0));
        
        
        //Table design
        Tabledesign(jTable1);
        
        
        //End Table design
    }
    Connection Con = null;
    Statement St = null;
    ResultSet Rs = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        formcontainer = new javax.swing.JPanel();
        Tabform = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        textField1 = new java.awt.TextField();
        choice1 = new java.awt.Choice();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        menu2 = new javax.swing.JPanel();
        Nutbanhang = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Nutnhaphang = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Nuthoadon = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Nutsanpham = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Nutkhuyenmai = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Nutkhachhang = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Nutnhanvien = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        Nutnhacungcap = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        Nuttaikhoan = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        header = new keeptoo.KGradientPanel();
        minclose = new javax.swing.JPanel();
        Nutthunho = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nutdong = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        formcontainer.setBackground(new java.awt.Color(35, 33, 77));
        formcontainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabform.setBackground(new java.awt.Color(255, 255, 255));
        Tabform.setPreferredSize(new java.awt.Dimension(900, 639));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(768, 639));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("A text 1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 128, 80));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(128, 128, 128));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(122, 72, 221));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 1100, 120));

        textField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textField1.setMinimumSize(new java.awt.Dimension(28, 25));
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        jPanel1.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 125, 220, 30));

        choice1.setMinimumSize(new java.awt.Dimension(28, 30));
        jPanel1.add(choice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 110, 100));

        jPanel10.setPreferredSize(new java.awt.Dimension(80, 24));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 130, 120, -1));

        jPanel12.setPreferredSize(new java.awt.Dimension(80, 24));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 120, -1));

        jPanel13.setPreferredSize(new java.awt.Dimension(80, 24));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 120, -1));

        jPanel14.setPreferredSize(new java.awt.Dimension(80, 24));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 120, -1));

        Tabform.addTab("tab1", jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("tab1");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1138, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );

        Tabform.addTab("tab2", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1138, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );

        Tabform.addTab("tab3", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1138, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );

        Tabform.addTab("tab4", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1138, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );

        Tabform.addTab("tab5", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1138, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );

        Tabform.addTab("tab6", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1138, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );

        Tabform.addTab("tab7", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1138, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );

        Tabform.addTab("tab8", jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1138, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );

        Tabform.addTab("tab9", jPanel9);

        formcontainer.add(Tabform, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1140, 710));

        getContentPane().add(formcontainer, java.awt.BorderLayout.CENTER);

        menu2.setBackground(new java.awt.Color(32, 30, 69));
        menu2.setPreferredSize(new java.awt.Dimension(225, 400));
        menu2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nutbanhang.setBackground(new java.awt.Color(32, 30, 69));
        Nutbanhang.setPreferredSize(new java.awt.Dimension(220, 70));
        Nutbanhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NutbanhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NutbanhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NutbanhangMouseExited(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlicuahangdienthoai/icons/icons8-shopping-cart-48 (1).png"))); // NOI18N
        jLabel8.setText("Bán hàng");

        javax.swing.GroupLayout NutbanhangLayout = new javax.swing.GroupLayout(Nutbanhang);
        Nutbanhang.setLayout(NutbanhangLayout);
        NutbanhangLayout.setHorizontalGroup(
            NutbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NutbanhangLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 64, Short.MAX_VALUE))
        );
        NutbanhangLayout.setVerticalGroup(
            NutbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        menu2.add(Nutbanhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));

        Nutnhaphang.setBackground(new java.awt.Color(32, 30, 69));
        Nutnhaphang.setPreferredSize(new java.awt.Dimension(220, 70));
        Nutnhaphang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NutnhaphangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NutnhaphangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NutnhaphangMouseExited(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlicuahangdienthoai/icons/icons8-packing-48.png"))); // NOI18N
        jLabel9.setText("Nhập hàng");

        javax.swing.GroupLayout NutnhaphangLayout = new javax.swing.GroupLayout(Nutnhaphang);
        Nutnhaphang.setLayout(NutnhaphangLayout);
        NutnhaphangLayout.setHorizontalGroup(
            NutnhaphangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NutnhaphangLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );
        NutnhaphangLayout.setVerticalGroup(
            NutnhaphangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jLabel9.getAccessibleContext().setAccessibleName("Nhập Hàng");
        jLabel9.getAccessibleContext().setAccessibleDescription("");

        menu2.add(Nutnhaphang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 230, -1));

        Nuthoadon.setBackground(new java.awt.Color(32, 30, 69));
        Nuthoadon.setPreferredSize(new java.awt.Dimension(220, 70));
        Nuthoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NuthoadonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NuthoadonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NuthoadonMouseExited(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlicuahangdienthoai/icons/icons8-cheque-48.png"))); // NOI18N
        jLabel10.setText("Hóa đơn");

        javax.swing.GroupLayout NuthoadonLayout = new javax.swing.GroupLayout(Nuthoadon);
        Nuthoadon.setLayout(NuthoadonLayout);
        NuthoadonLayout.setHorizontalGroup(
            NuthoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NuthoadonLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 69, Short.MAX_VALUE))
        );
        NuthoadonLayout.setVerticalGroup(
            NuthoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        menu2.add(Nuthoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 230, -1));

        Nutsanpham.setBackground(new java.awt.Color(32, 30, 69));
        Nutsanpham.setPreferredSize(new java.awt.Dimension(220, 70));
        Nutsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NutsanphamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NutsanphamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NutsanphamMouseExited(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlicuahangdienthoai/icons/icons8-aliexpress-48.png"))); // NOI18N
        jLabel11.setText("Sản phẩm");

        javax.swing.GroupLayout NutsanphamLayout = new javax.swing.GroupLayout(Nutsanpham);
        Nutsanpham.setLayout(NutsanphamLayout);
        NutsanphamLayout.setHorizontalGroup(
            NutsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NutsanphamLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );
        NutsanphamLayout.setVerticalGroup(
            NutsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        menu2.add(Nutsanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 230, -1));

        Nutkhuyenmai.setBackground(new java.awt.Color(32, 30, 69));
        Nutkhuyenmai.setPreferredSize(new java.awt.Dimension(220, 70));
        Nutkhuyenmai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NutkhuyenmaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NutkhuyenmaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NutkhuyenmaiMouseExited(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlicuahangdienthoai/icons/icons8-price-tag-48.png"))); // NOI18N
        jLabel12.setText("Khuyến mãi");

        javax.swing.GroupLayout NutkhuyenmaiLayout = new javax.swing.GroupLayout(Nutkhuyenmai);
        Nutkhuyenmai.setLayout(NutkhuyenmaiLayout);
        NutkhuyenmaiLayout.setHorizontalGroup(
            NutkhuyenmaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NutkhuyenmaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        NutkhuyenmaiLayout.setVerticalGroup(
            NutkhuyenmaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        menu2.add(Nutkhuyenmai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 230, -1));

        Nutkhachhang.setBackground(new java.awt.Color(32, 30, 69));
        Nutkhachhang.setPreferredSize(new java.awt.Dimension(220, 70));
        Nutkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NutkhachhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NutkhachhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NutkhachhangMouseExited(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlicuahangdienthoai/icons/icons8-user-48.png"))); // NOI18N
        jLabel16.setText("Khách hàng");

        javax.swing.GroupLayout NutkhachhangLayout = new javax.swing.GroupLayout(Nutkhachhang);
        Nutkhachhang.setLayout(NutkhachhangLayout);
        NutkhachhangLayout.setHorizontalGroup(
            NutkhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NutkhachhangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        NutkhachhangLayout.setVerticalGroup(
            NutkhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        menu2.add(Nutkhachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 230, -1));

        Nutnhanvien.setBackground(new java.awt.Color(32, 30, 69));
        Nutnhanvien.setPreferredSize(new java.awt.Dimension(220, 70));
        Nutnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NutnhanvienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NutnhanvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NutnhanvienMouseExited(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlicuahangdienthoai/icons/icons8-id-card-48.png"))); // NOI18N
        jLabel17.setText("Nhân viên");
        jLabel17.setIconTextGap(8);

        javax.swing.GroupLayout NutnhanvienLayout = new javax.swing.GroupLayout(Nutnhanvien);
        Nutnhanvien.setLayout(NutnhanvienLayout);
        NutnhanvienLayout.setHorizontalGroup(
            NutnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NutnhanvienLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 60, Short.MAX_VALUE))
        );
        NutnhanvienLayout.setVerticalGroup(
            NutnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        menu2.add(Nutnhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 230, -1));

        Nutnhacungcap.setBackground(new java.awt.Color(32, 30, 69));
        Nutnhacungcap.setPreferredSize(new java.awt.Dimension(220, 70));
        Nutnhacungcap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NutnhacungcapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NutnhacungcapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NutnhacungcapMouseExited(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlicuahangdienthoai/icons/icons8-skyscrapers-48.png"))); // NOI18N
        jLabel18.setText("Nhà cung cấp");
        jLabel18.setIconTextGap(6);

        javax.swing.GroupLayout NutnhacungcapLayout = new javax.swing.GroupLayout(Nutnhacungcap);
        Nutnhacungcap.setLayout(NutnhacungcapLayout);
        NutnhacungcapLayout.setHorizontalGroup(
            NutnhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NutnhacungcapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        NutnhacungcapLayout.setVerticalGroup(
            NutnhacungcapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        menu2.add(Nutnhacungcap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 230, -1));

        Nuttaikhoan.setBackground(new java.awt.Color(32, 30, 69));
        Nuttaikhoan.setPreferredSize(new java.awt.Dimension(220, 70));
        Nuttaikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NuttaikhoanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NuttaikhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NuttaikhoanMouseExited(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlicuahangdienthoai/icons/icons8-user-folder-48.png"))); // NOI18N
        jLabel19.setText("Tài khoản");
        jLabel19.setIconTextGap(8);

        javax.swing.GroupLayout NuttaikhoanLayout = new javax.swing.GroupLayout(Nuttaikhoan);
        Nuttaikhoan.setLayout(NuttaikhoanLayout);
        NuttaikhoanLayout.setHorizontalGroup(
            NuttaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NuttaikhoanLayout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 62, Short.MAX_VALUE))
        );
        NuttaikhoanLayout.setVerticalGroup(
            NuttaikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        menu2.add(Nuttaikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 230, -1));

        getContentPane().add(menu2, java.awt.BorderLayout.LINE_START);

        header.setkEndColor(new java.awt.Color(92, 37, 141));
        header.setkGradientFocus(650);
        header.setkStartColor(new java.awt.Color(67, 137, 162));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        minclose.setBackground(new java.awt.Color(92, 37, 141));
        minclose.setMinimumSize(new java.awt.Dimension(100, 100));
        minclose.setPreferredSize(new java.awt.Dimension(150, 100));
        minclose.setLayout(new java.awt.BorderLayout());

        Nutthunho.setBackground(new java.awt.Color(92, 37, 141));
        Nutthunho.setMinimumSize(new java.awt.Dimension(75, 50));
        Nutthunho.setPreferredSize(new java.awt.Dimension(50, 50));
        Nutthunho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NutthunhoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NutthunhoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NutthunhoMousePressed(evt);
            }
        });
        Nutthunho.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlicuahangdienthoai/icons/icons8-subtract-30.png"))); // NOI18N
        Nutthunho.add(jLabel1, java.awt.BorderLayout.CENTER);

        minclose.add(Nutthunho, java.awt.BorderLayout.LINE_START);

        Nutdong.setBackground(new java.awt.Color(92, 37, 141));
        Nutdong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NutdongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NutdongMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NutdongMousePressed(evt);
            }
        });
        Nutdong.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlicuahangdienthoai/icons/icons8-close-30.png"))); // NOI18N
        Nutdong.add(jLabel2, java.awt.BorderLayout.CENTER);

        minclose.add(Nutdong, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 1396, Short.MAX_VALUE)
                .addComponent(minclose, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(minclose, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    //Table design function
    public void Tabledesign(JTable tab){
        tab.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tab.getTableHeader().setOpaque(false);
        tab.getTableHeader().setBackground(new Color(32,136,203));
        tab.getTableHeader().setForeground(new Color(255,255,255));
        tab.getTableHeader().setBorder(BorderFactory.createEmptyBorder());
        tab.setRowHeight(25);
    }
    
    
    //Table design function
    public void changecolor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }
    
    private void NutthunhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutthunhoMouseEntered
       changecolor(Nutthunho, new Color(74,30,113));
    }//GEN-LAST:event_NutthunhoMouseEntered

    private void NutthunhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutthunhoMouseExited
       changecolor(Nutthunho, new Color(92,37,141));
    }//GEN-LAST:event_NutthunhoMouseExited

    private void NutthunhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutthunhoMousePressed
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_NutthunhoMousePressed

    private void NutdongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutdongMouseEntered
        changecolor(Nutdong, new Color(74,30,113));
    }//GEN-LAST:event_NutdongMouseEntered

    private void NutdongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutdongMouseExited
        changecolor(Nutdong, new Color(92,37,141));
    }//GEN-LAST:event_NutdongMouseExited

    private void NutdongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutdongMousePressed
        System.exit(0);
    }//GEN-LAST:event_NutdongMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
       int cordX = evt.getXOnScreen();
       int cordY = evt.getYOnScreen();
       
       this.setLocation(cordX - mouseX,cordY - mouseY);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void NutbanhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutbanhangMouseEntered
        changecolor(Nutbanhang,new Color(37,39,84));
    }//GEN-LAST:event_NutbanhangMouseEntered

    private void NutbanhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutbanhangMouseExited
        changecolor(Nutbanhang,new Color(32,30,69));
    }//GEN-LAST:event_NutbanhangMouseExited

    private void NutbanhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutbanhangMouseClicked
        Tabform.setSelectedIndex(0);
        changecolor(Nutbanhang,new Color(56, 58, 105));
        changecolor(Nutnhaphang,new Color(32,30,69));
        changecolor(Nutkhachhang,new Color(32,30,69));
        changecolor(Nutkhuyenmai,new Color(32,30,69));
        changecolor(Nutnhacungcap,new Color(32,30,69));
        changecolor(Nutnhanvien,new Color(32,30,69));
        changecolor(Nutnhaphang,new Color(32,30,69));
        changecolor(Nutsanpham,new Color(32,30,69));
        changecolor(Nuttaikhoan,new Color(32,30,69));
    }//GEN-LAST:event_NutbanhangMouseClicked

    private void NutnhaphangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutnhaphangMouseEntered
        // TODO add your handling code here:
        changecolor(Nutnhaphang,new Color(37,39,84));
    }//GEN-LAST:event_NutnhaphangMouseEntered

    private void NutnhaphangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutnhaphangMouseExited
        // TODO add your handling code here:
        changecolor(Nutnhaphang,new Color(32,30,69));
    }//GEN-LAST:event_NutnhaphangMouseExited

    private void NutnhaphangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutnhaphangMouseClicked
        // TODO add your handling code here:
        Tabform.setSelectedIndex(1);
    }//GEN-LAST:event_NutnhaphangMouseClicked

    private void NuthoadonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuthoadonMouseEntered
        // TODO add your handling code here:
        changecolor(Nuthoadon,new Color(37,39,84));
    }//GEN-LAST:event_NuthoadonMouseEntered

    private void NuthoadonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuthoadonMouseExited
        // TODO add your handling code here:
        changecolor(Nuthoadon,new Color(32,30,69));
    }//GEN-LAST:event_NuthoadonMouseExited

    private void NuthoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuthoadonMouseClicked
        // TODO add your handling code here:
        Tabform.setSelectedIndex(2);
    }//GEN-LAST:event_NuthoadonMouseClicked

    private void NutsanphamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutsanphamMouseEntered
        // TODO add your handling code here:
        changecolor(Nutsanpham,new Color(37,39,84));
    }//GEN-LAST:event_NutsanphamMouseEntered

    private void NutsanphamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutsanphamMouseExited
        // TODO add your handling code here:
        changecolor(Nutsanpham,new Color(32,30,69));
    }//GEN-LAST:event_NutsanphamMouseExited

    private void NutsanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutsanphamMouseClicked
        // TODO add your handling code here:
        Tabform.setSelectedIndex(3);
    }//GEN-LAST:event_NutsanphamMouseClicked

    private void NutkhuyenmaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutkhuyenmaiMouseEntered
        // TODO add your handling code here:
        changecolor(Nutkhuyenmai,new Color(37,39,84));
    }//GEN-LAST:event_NutkhuyenmaiMouseEntered

    private void NutkhuyenmaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutkhuyenmaiMouseExited
        // TODO add your handling code here:
        changecolor(Nutkhuyenmai,new Color(32,30,69));
    }//GEN-LAST:event_NutkhuyenmaiMouseExited

    private void NutkhuyenmaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutkhuyenmaiMouseClicked
        // TODO add your handling code here:
        Tabform.setSelectedIndex(4);
    }//GEN-LAST:event_NutkhuyenmaiMouseClicked

    private void NutkhachhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutkhachhangMouseEntered
        // TODO add your handling code here:
        changecolor(Nutkhachhang,new Color(37,39,84));
    }//GEN-LAST:event_NutkhachhangMouseEntered

    private void NutkhachhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutkhachhangMouseExited
        // TODO add your handling code here:
        changecolor(Nutkhachhang,new Color(32,30,69));
    }//GEN-LAST:event_NutkhachhangMouseExited

    private void NutkhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutkhachhangMouseClicked
        // TODO add your handling code here:
        Tabform.setSelectedIndex(5);
    }//GEN-LAST:event_NutkhachhangMouseClicked

    private void NutnhanvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutnhanvienMouseEntered
        // TODO add your handling code here:
        changecolor(Nutnhanvien,new Color(37,39,84));
    }//GEN-LAST:event_NutnhanvienMouseEntered

    private void NutnhanvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutnhanvienMouseExited
        // TODO add your handling code here:
        changecolor(Nutnhanvien,new Color(32,30,69));
    }//GEN-LAST:event_NutnhanvienMouseExited

    private void NutnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutnhanvienMouseClicked
        // TODO add your handling code here:
        Tabform.setSelectedIndex(6);
    }//GEN-LAST:event_NutnhanvienMouseClicked

    private void NutnhacungcapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutnhacungcapMouseEntered
        // TODO add your handling code here:
        changecolor(Nutnhacungcap,new Color(37,39,84));
    }//GEN-LAST:event_NutnhacungcapMouseEntered

    private void NutnhacungcapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutnhacungcapMouseExited
        // TODO add your handling code here:
        changecolor(Nutnhacungcap,new Color(32,30,69));
    }//GEN-LAST:event_NutnhacungcapMouseExited

    private void NutnhacungcapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NutnhacungcapMouseClicked
        // TODO add your handling code here:
        Tabform.setSelectedIndex(7);
    }//GEN-LAST:event_NutnhacungcapMouseClicked

    private void NuttaikhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuttaikhoanMouseEntered
        // TODO add your handling code here:
        changecolor(Nuttaikhoan,new Color(37,39,84));
    }//GEN-LAST:event_NuttaikhoanMouseEntered

    private void NuttaikhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuttaikhoanMouseExited
        // TODO add your handling code here:
        changecolor(Nuttaikhoan,new Color(32,30,69));
    }//GEN-LAST:event_NuttaikhoanMouseExited

    private void NuttaikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuttaikhoanMouseClicked
        // TODO add your handling code here:
        Tabform.setSelectedIndex(8);
    }//GEN-LAST:event_NuttaikhoanMouseClicked

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    
    
  
    
    
    
    public static void main(String args[]) {
        System.setProperty("sun.java2d.uiScale", "1.0");
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Nutbanhang;
    private javax.swing.JPanel Nutdong;
    private javax.swing.JPanel Nuthoadon;
    private javax.swing.JPanel Nutkhachhang;
    private javax.swing.JPanel Nutkhuyenmai;
    private javax.swing.JPanel Nutnhacungcap;
    private javax.swing.JPanel Nutnhanvien;
    private javax.swing.JPanel Nutnhaphang;
    private javax.swing.JPanel Nutsanpham;
    private javax.swing.JPanel Nuttaikhoan;
    private javax.swing.JPanel Nutthunho;
    private javax.swing.JTabbedPane Tabform;
    private java.awt.Choice choice1;
    private javax.swing.JPanel formcontainer;
    private keeptoo.KGradientPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel menu2;
    private javax.swing.JPanel minclose;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables


